spring:
  application:
    name: demo-spring-boot
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: "secret"
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create